---
  - name: PHP
    apt: name=software-properties-common

  - name: Add co-installable PHP 7.2
    apt_repository: 
     repo: 'ppa:ondrej/php'

  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  
  - name: Install PHP Extensions and PyMysql
    apt: name={{item}} state=latest
    with_items:
      - php
      - libapache2-mod-php
      - php-common
      - php-gmp
      - php-curl
      - php-intl
      - php-mbstring
      - php-xmlrpc
      - php-mysql
      - php-gd
      - php-bcmath
      - php-xml
      - php-cli
      - php-zip
      - php-sqlite3
      - php-ldap
      - python3
      - python3-mysqldb
